export interface AltaMp {
    descripcion:string,
    tipo : string,
    ubicacion : string,
    riesgo : string,
    proteccion : string,
    precio :number,
    pesoespecifico :number,
    solidosppp :number,
    solidosppv :number,
    resina :number,
    pigmento :number,
    solvente :number,
    stock :number,
    stockminimo :number,
    unidadmedidacompra : string,
    codpt :number,
    condaprob1 : string,
    condaprob2 : string,
    condaprob3 : string,
    condaprob4 : string,
    info1 : string,
    info2 : string,
    info3 : string,
    cobarras :number,
    fechaultimarecepcion: string;
}