import { Component, OnInit } from '@angular/core';
import { GenericService } from '../../services/generic.service';

@Component({
  selector: 'app-verificacion',
  templateUrl: './verificacion.component.html',
  styleUrls: ['./verificacion.component.css']
})
export class VerificacionComponent implements OnInit {

  // Fecha (Generated by the backend)
  public operario: string; 
  public codigomp: number; 
  public lote: number;
  // ok(boolean) (Sending the verification, we validate the data sent by the user,
  // and we determinate the ok field seeing the repsonse)


  constructor(private genericService: GenericService) { }

  ngOnInit(): void {
  }

  traerDescripcion() {
    this.genericService.traerDescripcion(this.codigomp)
    .subscribe( data => {
      console.log(data);
    }, err => {
      console.log(err);
    })
  }

  enviarData() {
    let enviar: boolean = true;
    /** VALIDACION GENERICA **/
    ['codigomp', 'lote', 'operario'].forEach((item) => {
      if(!this[item]){
        enviar = false;
      };

    });
    
    if(!enviar){ 
      /** Enviar feedback */
      return; 
    };

    let data = { 
      codigomp: this.codigomp,
      lote: this.lote,
      operario: this.operario
    };

    this.genericService.agregarVerificacion(data)
    .subscribe( data => {
      console.log(data);
    }, err => {
      console.log(err);
    })
  }

}
