import { Component, OnInit } from '@angular/core';
import { GenericService } from '../../services/generic.service';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-verificacion',
  templateUrl: './verificacion.component.html',
  styleUrls: ['./verificacion.component.css']
})
export class VerificacionComponent implements OnInit {

  // Fecha (Generated by the backend)
  public operario: string;
  public codigomp: number;
  public lote: number;
  public partida: number;
  public descripcion: string;

  // ok(boolean) (Sending the verification, we validate the data sent by the user,
  // and we determinate the ok field seeing the repsonse)


  constructor(private genericService: GenericService) { }

  ngOnInit(): void {
  }

  traerDescripcion() {  //tiene que traerlo de la base de datos materia prima
    this.genericService.traerDescripcion(this.codigomp)
      .subscribe((data: any) => {
        console.log(data);
        this.descripcion = data.response[0].descripcion;
      }, err => {
        console.log(err);  // poner mensaje alertify  "no existe esa materia prima"
      })
  }

  enviarData() {
    let enviar: boolean = true;
    /** VALIDACION GENERICA **/
    ['codigomp', 'lote', 'operario', 'partida'].forEach((item) => {
      if (!this[item]) {
        enviar = false;
      };

    });

    if (!enviar) {
      /** Enviar feedback */
      return;
    };

    let data = {
      codigomp: this.codigomp,
      lote: this.lote,
      operario: this.operario,
      partida: this.partida
    };

    this.genericService.agregarVerificacion(data)
      .subscribe((data: any) => {
        console.log(data);

        if (data.ok == "false") {
          return Swal.fire({
            title: "ALERTA",
            text: "NO COINCIDE MATERIA PRIMA CON NUMERO DE LOTE",
            icon: "error"
          })
        } else {
          let timerInterval
          Swal.fire({
            title: 'Verificacion correcta ',
            timer: 3000,
            timerProgressBar: true,
            onBeforeOpen: () => {
              Swal.showLoading()
              timerInterval = setInterval(() => {
              }, 100)
            },
            onClose: () => {
              clearInterval(timerInterval)
              this.resetear()
            }
          }).then((result) => {
            /* Read more about handling dismissals below */
            if (result.dismiss === Swal.DismissReason.timer) {
              console.log('I was closed by the timer')
            }
          })
        }

      }, err => {
        console.log(err);
      })
  }

  resetear() {
    this.codigomp = null;
    this.lote = null;
    this.operario = null;
    this.partida = null;
    // como se borra la descripcion que puse cuando encuentra la materia prima
  }
}