import { Component, OnInit } from '@angular/core';
import { GenericService } from '../../services/generic.service';
import Swal from 'sweetalert2';
import { NumberValueAccessor } from '@angular/forms';
declare let alertify: any;

@Component({
  selector: 'app-verificacion',
  templateUrl: './verificacion.component.html',
  styleUrls: ['./verificacion.component.css']
})
export class VerificacionComponent implements OnInit {

  // Fecha (Generated by the backend)
  public operario: string;
  public codigomp: number;
  public lote: number;
  public partida: number;
  public descripcion: string;
  public descripcionLote: string;
  public descripcionPartida: Number;
  public aprobado: string;
  public partidaok = false;         // para que no se pueda poner partidas terminadas

  // ok(boolean) (Sending the verification, we validate the data sent by the user,
  // and we determinate the ok field seeing the repsonse)


  constructor(private genericService: GenericService) { }

  ngOnInit(): void {
  }

  traerDescripcion() {  //tiene que traerlo de la base de datos materia prima
    this.genericService.traerDescripcion(this.codigomp)
      .subscribe((data: any) => {
        this.descripcion = data.response[0].descripcion;
      }, err => {
        alertify.error("ESA MATERIA PRIMA NO SE COMPRO HACE AÑOS");
      })
  }

  traerLote() {  //tiene que traerlo de la base de datos materia prima
    this.genericService.traerLote(this.lote)
      .subscribe((data: any) => {
        this.descripcionLote = data.response[0].descripcion;
      }, err => {
        alertify.error("LOTE ERRONEO O EQUIVOCADO");
      })
  }

  traerPartida() {  //tiene que traerlo de la base de datos calidad PT
    this.genericService.traerPartida(this.partida)
      .subscribe((data: any) => {
        if (data?.response?.length) {
          this.descripcionPartida = data.response[0].numeroPartida;
          if (data.response[0].aprobado) {
            alertify.error("La partida ESTA FINALIZADA");
          } else {
            this.partidaok = true;
          }
        } else {
          alertify.error("No se encontró la partida solicitada.");
          this.partidaok = false;
        }
      }, err => {
        alertify.error("Ocurrió un error al obtener la partida.");
        this.partidaok = false;
      })
  }

  //traerPartida() {  
  //  this.genericService.traerPartida(this.partida)
  //    .subscribe((data: any) => {
  //      this.descripcionPartida = data.response[0].numeroPartida;
  //  
  //      console.log(this.descripcionPartida);
  //      console.log(this.aprobado);
  //    }, err => {
  //      this.partida = null;
  //      alertify.error("PARTIDA INEXISTENTE");
  //    })
  //}

  enviarData() {
    let enviar: boolean = true;
    /** VALIDACION GENERICA **/
    ['codigomp', 'lote', 'operario', 'partida'].forEach((item) => {
      if (!this[item]) {
        enviar = false;
      };

    });

    if (!enviar) {
      /** Enviar feedback */
      return;
    };

    let data = {
      codigomp: this.codigomp,
      lote: this.lote,
      operario: this.operario,
      partida: this.partida,
    };

    this.genericService.agregarVerificacion(data)
      .subscribe((data: any) => {

        if (data.ok == "false") {
          Swal.fire({
            title: "ALERTA",
            imageUrl: "./assets/imagen_NO_ok_2.jpeg",
            imageWidth: 400,
            imageHeight: 200,
            text: "NO COINCIDE MATERIA PRIMA CON NUMERO DE LOTE",
          })
        } else {
          let timerInterval
          Swal.fire({
            title: 'Verificacion correcta ',
            imageUrl: "./assets/imagen_ok.jpg",
            imageWidth: 400,
            imageHeight: 200,
            timer: 2500,
            timerProgressBar: true,
            onBeforeOpen: () => {
              Swal.showLoading()
              timerInterval = setInterval(() => {
              }, 100)
            },
            onClose: () => {
              clearInterval(timerInterval)
            }
          }).then((result) => {
            /* Read more about handling dismissals below */
            if (result.dismiss === Swal.DismissReason.timer) {
            }
          })
        }
        this.resetear()
      }, err => {
        console.log(err);
      })
  }

  resetear() {
    this.codigomp = null;
    this.lote = null;
    this.operario = null;
    this.partida = null;
    this.descripcion = null;
    this.descripcionLote = null;
    this.descripcionPartida = null;
    this.partidaok = false;
  }
}